export const data = {
  subject: [
    { id: 1, text: 'Lone tree' },
    { id: 2, text: 'Old man reading' },
    { id: 3, text: 'Curious child' },
    { id: 4, text: 'Samurai warrior' },
    { id: 5, text: 'Ballerina' },
    { id: 6, text: 'Spaceship' },
    { id: 7, text: 'Grandfather clock' },
    { id: 8, text: 'Koi fish' },
    { id: 9, text: 'White horse' },
    { id: 10, text: 'Surfer' },
    { id: 11, text: 'Lady with Victorian-era clothing' },
    { id: 12, text: 'Majestic lion' },
    { id: 13, text: 'Saxophonist' },
    { id: 14, text: 'Street artist' },
    { id: 15, text: 'Vintage car' },
    { id: 16, text: 'Wild deer' },
    { id: 17, text: 'Glassblower' },
    { id: 18, text: 'Fairy' },
    { id: 19, text: 'Ancient warrior' },
    { id: 20, text: 'Antique map' },
    { id: 21, text: 'Fireflies' },
    { id: 22, text: 'Orangutan' },
    { id: 23, text: 'Dancer' },
    { id: 24, text: 'Scuba diver' },
    { id: 25, text: 'Old woman knitting' },
    { id: 26, text: 'Moroccan woman in traditional attire' },
    { id: 27, text: 'Pegasus' },
    { id: 28, text: 'Chess master' },
    { id: 29, text: 'Astronaut' },
    { id: 30, text: 'Polar bear' },
    { id: 31, text: 'Monarch butterflies' },
    { id: 32, text: 'Viking' },
    { id: 33, text: 'Samurai' },
    { id: 34, text: 'Musketeer' },
    { id: 35, text: 'Gondolier' },
    { id: 36, text: 'Geisha' },
    { id: 37, text: 'Honeybee' },
    { id: 38, text: 'Phantom' },
    { id: 39, text: 'Writer' },
    { id: 40, text: 'Pizza chef' },
    { id: 41, text: 'Flamenco dancer' },
    { id: 42, text: 'Ninja' },
    { id: 43, text: 'Peregrine falcon' },
    { id: 44, text: 'Pirate' },
    { id: 45, text: 'Bengal tiger' },
    { id: 46, text: 'Matador' },
    { id: 47, text: 'Street magician' },
    { id: 48, text: 'Swans' },
    { id: 49, text: 'Ancient Egyptian priestess' },
    { id: 50, text: 'Hot air balloons' },
    { id: 51, text: 'Aboriginal dancer' },
    { id: 52, text: 'Rhinoceros' },
    { id: 53, text: 'Baker' },
    { id: 54, text: 'Mermaid' },
    { id: 55, text: 'Snow leopard' },
    { id: 56, text: 'Astronomer' },
    { id: 57, text: 'Jazz band' },
    { id: 58, text: 'Sherpa' },
    { id: 59, text: 'Peacock' },
    { id: 60, text: 'Knight' },
    { id: 61, text: 'Wolves' },
    { id: 62, text: 'Tattoo artist' },
    { id: 63, text: 'Graffiti artist' },
    { id: 64, text: 'Young girl with a lantern' },
    { id: 65, text: 'Cherry blossoms' },
    { id: 66, text: 'Quokka' },
    { id: 67, text: 'Opera singer' },
    { id: 68, text: 'Young monks' },
    { id: 69, text: 'Flamingos' },
    { id: 70, text: 'Dapper gentleman' },
    { id: 71, text: 'Tango dancers' },
    { id: 72, text: 'Eagle' },
    { id: 73, text: 'Tea master' },
    { id: 74, text: 'Camels' },
    { id: 75, text: 'Husky dog sled team' },
    { id: 76, text: 'Highland cattle' },
    { id: 77, text: 'Cyclist' },
    { id: 78, text: 'Hiker' },
    { id: 79, text: 'Sushi chef' },
    { id: 80, text: 'Steam train' },
    { id: 81, text: 'Macaws' },
    { id: 82, text: 'Elephant' },
    { id: 83, text: 'Cowboys' },
    { id: 84, text: 'Anglerfish' },
    { id: 85, text: 'Bull rider' },
    { id: 86, text: 'Ship in a bottle' },
    { id: 87, text: 'Lavender field' },
    { id: 88, text: 'Parkour athlete' },
    { id: 89, text: 'Arabian horse' },
    { id: 90, text: 'Black panther' },
    { id: 91, text: 'Capoeira fighter' },
    { id: 92, text: "1950's style pin-up girl" },
    { id: 93, text: 'Mysterious hooded figure' },
    { id: 94, text: 'Husky' },
    { id: 95, text: 'Water buffalo' },
    { id: 96, text: 'Shepherd with his flock' },
    { id: 97, text: 'Tarantula' },
    { id: 98, text: 'Swan on a lake' },
    { id: 99, text: 'Moose' },
    { id: 100, text: 'Paraglider' },
    { id: 101, text: 'Mickey Mouse' },
    { id: 102, text: 'Bugs Bunny' },
    { id: 103, text: 'Bart Simpson' },
    { id: 104, text: 'SpongeBob SquarePants' },
    { id: 105, text: 'Scooby-Doo' },
    { id: 106, text: 'Charlie Brown' },
    { id: 107, text: 'Homer Simpson' },
    { id: 108, text: 'Hulk' },
    { id: 109, text: 'Winnie the Pooh' },
    { id: 110, text: 'Donald Duck' },
    { id: 111, text: 'Daffy Duck' },
    { id: 112, text: 'Tweety Bird' },
    { id: 113, text: 'Popeye' },
    { id: 114, text: 'Winnie the Pooh' },
    { id: 115, text: 'Pink Panther' },
    { id: 116, text: 'Pikachu' },
    { id: 117, text: 'Naruto Uzumaki' },
    { id: 118, text: 'Goku' },
    { id: 119, text: 'Superman' },
    { id: 120, text: 'Batman' },
    { id: 121, text: 'Spider-Man' },
    { id: 122, text: 'Wonder Woman' },
    { id: 123, text: 'Leonardo' },
    { id: 124, text: 'Blossom' },
    { id: 125, text: 'Hello Kitty' },
    { id: 126, text: 'Peppa Pig' },
    { id: 127, text: 'Elsa' },
    { id: 128, text: 'Woody' },
    { id: 129, text: 'Buzz Lightyear' },
    { id: 130, text: 'Shrek' },
    { id: 131, text: 'Patrick Star' },
    { id: 132, text: 'Marge Simpson' },
    { id: 133, text: 'Bob the Builder' },
    { id: 134, text: 'Dora the Explorer' },
    { id: 135, text: 'Ariel' },
    { id: 136, text: 'Cinderella' },
    { id: 137, text: 'Snow White' },
    { id: 138, text: 'Belle' },
    { id: 139, text: 'Tinker Bell' },
    { id: 140, text: 'Simba' },
    { id: 141, text: 'Iron Man' },
    { id: 142, text: 'Captain America' },
    { id: 143, text: 'Thor' },
    { id: 144, text: 'Groot' },
    { id: 145, text: 'Stitch' },
    { id: 146, text: 'Deadpool' },
    { id: 147, text: 'Aladdin' },
    { id: 148, text: 'Totoro' },
    { id: 149, text: 'Astro Boy' },
    { id: 150, text: 'Sonic the Hedgehog' },
  ],
  setting: [
    { id: 1, text: 'Sunrise over the misty mountains' },
    { id: 2, text: 'Cozy bookstore' },
    { id: 3, text: 'Vibrant candy shop' },
    { id: 4, text: 'Cherry blossom festival' },
    { id: 5, text: 'Abandoned industrial building' },
    { id: 6, text: 'Outer space with galaxies and nebulae' },
    { id: 7, text: 'Gothic library' },
    { id: 8, text: 'Garden pond with floating lotus flowers' },
    { id: 9, text: 'Snow-covered forest' },
    { id: 10, text: 'Glowing sunset on the beach' },
    { id: 11, text: 'Tea garden' },
    { id: 12, text: 'African savannah' },
    { id: 13, text: 'New Orleans French Quarter' },
    { id: 14, text: 'Graffiti-covered alleyway' },
    { id: 15, text: 'Route 66' },
    { id: 16, text: 'Pacific Northwest rainforest' },
    { id: 17, text: 'Ancient Venetian workshop' },
    { id: 18, text: 'Enchanted forest with glowing mushrooms' },
    { id: 19, text: 'Battleground amidst heavy rainfall' },
    { id: 20, text: "Explorer's study room" },
    { id: 21, text: 'Rural summer night' },
    { id: 22, text: 'Dense, lush tropical rainforest' },
    { id: 23, text: 'Colorful Holi festival in India' },
    { id: 24, text: 'Coral reef with vibrant marine life' },
    { id: 25, text: 'Rustic cottage fireplace' },
    { id: 26, text: 'Marrakech marketplace' },
    { id: 27, text: 'Mountain peak with a rainbow' },
    { id: 28, text: 'Outdoor park in Autumn' },
    { id: 29, text: 'Moon with Earth in the background' },
    { id: 30, text: 'Icy Arctic landscape' },
    { id: 31, text: 'Mexican forest during migration season' },
    { id: 32, text: 'Foggy Nordic fjords' },
    { id: 33, text: 'Japanese bamboo forest' },
    { id: 34, text: 'French Renaissance castle' },
    { id: 35, text: 'Venice canals at dusk' },
    { id: 36, text: 'Kyoto during cherry blossom season' },
    { id: 37, text: 'Field of sunflowers' },
    { id: 38, text: 'Haunted Victorian mansion' },
    { id: 39, text: 'Cozy Parisian café' },
    { id: 40, text: 'Old brick oven pizzeria in Naples' },
    { id: 41, text: 'Traditional tablao in Seville' },
    { id: 42, text: 'Ancient Japanese pagoda at night' },
    { id: 43, text: 'Rocky cliffs overlooking the sea' },
    { id: 44, text: 'Ship on the Caribbean Sea' },
    { id: 45, text: 'Sundarbans mangrove forest' },
    { id: 46, text: 'Spanish bullfighting ring' },
    { id: 47, text: 'Crowded London street' },
    { id: 48, text: 'Lake with castle ruins in the background' },
    { id: 49, text: 'Temple of Karnak' },
    { id: 50, text: 'Sunrise over Cappadocia' },
    { id: 51, text: 'Australian outback under the stars' },
    { id: 52, text: 'African savannah at sunset' },
    { id: 53, text: 'Old-world French patisserie' },
    { id: 54, text: 'Underwater coral kingdom' },
    { id: 55, text: 'Himalayan mountain range' },
    { id: 56, text: 'Observatory under a starlit sky' },
    { id: 57, text: 'New York rooftop under city lights' },
    { id: 58, text: 'Everest base camp' },
    { id: 59, text: 'Royal palace garden' },
    { id: 60, text: 'Medieval European castle' },
    { id: 61, text: 'Canadian wilderness under the northern lights' },
    { id: 62, text: 'Urban loft studio' },
    { id: 63, text: 'Subway tunnel' },
    { id: 64, text: 'Moonlit pumpkin patch' },
    { id: 65, text: 'Japanese Shinto shrine' },
    { id: 66, text: 'Australian bush with eucalyptus trees' },
    { id: 67, text: '19th-century opera house' },
    { id: 68, text: 'Bhutanese monastery in the Himalayas' },
    { id: 69, text: 'Salt flat with a pink lake' },
    { id: 70, text: 'Classic 1920s speakeasy' },
    { id: 71, text: 'Old street in Buenos Aires at night' },
    { id: 72, text: 'Grand Canyon during sunrise' },
    { id: 73, text: 'Chinese tea ceremony in an ancient garden' },
    { id: 74, text: 'Arabian desert under the stars' },
    { id: 75, text: 'Snowy Alaskan wilderness' },
    { id: 76, text: 'Scottish Highlands in fog' },
    { id: 77, text: 'Lush Tuscan countryside' },
    { id: 78, text: 'Top of Mount Fuji at dawn' },
    { id: 79, text: 'Tokyo fish market' },
    { id: 80, text: 'Countryside in Autumn' },
    { id: 81, text: 'Brazilian rainforest' },
    { id: 82, text: 'Indian festival with colorful decorations' },
    { id: 83, text: 'American West during a golden sunset' },
    { id: 84, text: 'Dark abyss of the deep sea' },
    { id: 85, text: 'American rodeo' },
    { id: 86, text: "Old sea captain's quarters" },
    { id: 87, text: 'Provence countryside' },
    { id: 88, text: 'Urban rooftop' },
    { id: 89, text: 'Ancient ruins in Petra, Jordan' },
    { id: 90, text: 'Rainforest at night' },
    { id: 91, text: 'Brazilian beach at sunset' },
    { id: 92, text: 'Classic American diner' },
    { id: 93, text: 'Cobblestone alley in medieval Europe' },
    { id: 94, text: 'Northern lights in Lapland' },
    { id: 95, text: 'Rice fields in Bali' },
    { id: 96, text: 'Green rolling hills of Ireland' },
    { id: 97, text: 'Desert under a full moon' },
    { id: 98, text: 'Misty English countryside' },
    { id: 99, text: 'Canadian forest in Autumn' },
    { id: 100, text: 'Over Swiss Alps with small village below' },
    { id: 101, text: 'Ancient Mayan temple' },
    { id: 102, text: 'Cave with a waterfall inside' },
    { id: 103, text: 'Cave with bioluminescent worms' },
    { id: 104, text: 'Cave with a hidden pirate treasure' },
    { id: 105, text: 'Cave with ancient hieroglyphics' },
    { id: 106, text: 'Cave with a sleeping dragon' },
    { id: 107, text: 'Cave with a giant crystal' },
    { id: 109, text: 'Cave with a hidden temple' },
    { id: 110, text: 'Cave with a giant tree' },
    { id: 111, text: 'Quiet monastery in the Himalayas' },
    { id: 112, text: 'Dense bamboo forest in the morning mist' },
    { id: 113, text: 'Vibrant marketplace in Marrakech' },
    { id: 114, text: 'Pristine snowfield under the Northern Lights' },
    { id: 115, text: 'Abandoned amusement park at dusk' },
    { id: 116, text: 'Lighthouse on a stormy sea' },
    { id: 117, text: 'Rainbow over a rolling green meadow' },
    { id: 118, text: 'Sunset over a bustling harbor' },
    { id: 119, text: 'Secluded beach with bioluminescent waves' },
    { id: 120, text: 'Night sky filled with shooting stars' },
    { id: 121, text: 'An oasis in the middle of a desert' },
    { id: 122, text: 'Old clock tower in a European city' },
    { id: 123, text: 'Grand ballroom in a royal castle' },
    { id: 124, text: 'Quiet library with antique books' },
    { id: 125, text: 'Street carnival with colorful costumes and floats' },
    { id: 126, text: 'Serene Zen garden with a koi pond' },
    { id: 127, text: 'Bustling kitchen of a famous Italian restaurant' },
    { id: 128, text: 'Cozy log cabin in a snowy forest' },
    { id: 129, text: 'Old western ghost town' },
    { id: 130, text: 'Fairy-tale castle surrounded by a moat' },
    { id: 131, text: 'Festival of lanterns in Thailand' },
    { id: 132, text: 'Morning dew on a spider’s web in the forest' },
    { id: 133, text: 'Jazz club in New Orleans' },
    { id: 134, text: 'Wheat fields waving in the breeze' },
    { id: 135, text: 'Sunrise over a calm lake' },
    { id: 136, text: 'Ornate gondolas in Venetian canals' },
    { id: 137, text: 'Lavender fields in Provence' },
    { id: 138, text: 'An ancient library filled with scrolls' },
    { id: 139, text: 'Lighthouse illuminating a foggy night' },
    { id: 140, text: 'Maasai warriors dancing at sunset' },
    { id: 141, text: 'Steaming geysers in Iceland' },
    { id: 142, text: 'Old vineyard in the Tuscan hills' },
    { id: 143, text: 'Antique shop filled with curiosities' },
    { id: 144, text: 'Bustling silk market in Shanghai' },
    { id: 145, text: 'Majestic eagles soaring over the Grand Canyon' },
    { id: 146, text: 'Shimmering bioluminescent bay in Puerto Rico' },
    { id: 147, text: 'Blooming cherry trees in a Japanese garden' },
    { id: 148, text: 'Floating market in Bangkok' },
    { id: 149, text: 'Dusty books in an attic' },
    { id: 150, text: 'Sunset over Santorini’s white buildings' },
    { id: 151, text: 'Tea plantation in the misty mountains' },
    { id: 152, text: 'Snowy day in a quiet village' },
    { id: 153, text: 'Classic cars on the streets of Havana' },
    { id: 154, text: 'Abandoned castle overtaken by nature' },
    { id: 155, text: 'A roaring waterfall in a tropical jungle' },
    { id: 156, text: 'A bustling fish market in Tokyo' },
    { id: 157, text: 'A hidden hot spring in the mountains' },
    { id: 158, text: 'A serene temple garden in Kyoto' },
    { id: 159, text: 'A quiet café in Paris' },
    { id: 160, text: 'A lively bazaar in Istanbul' },
    { id: 161, text: 'A mysterious forest covered in fog' },
    { id: 162, text: 'A forgotten ghost town in the desert' },
    { id: 163, text: 'A secret garden hidden behind an old mansion' },
    { id: 164, text: 'A quiet mountain top overlooking a vast valley' },
    { id: 165, text: 'A beautiful coral reef teeming with marine life' },
    { id: 166, text: 'A colorful carnival parade in Rio de Janeiro' },
    { id: 167, text: 'A peaceful beach at sunset in Bali' },
    { id: 168, text: 'An ancient stone temple in Cambodia' },
    { id: 169, text: 'A bustling street market in Mumbai' },
    { id: 170, text: 'A tranquil bamboo forest in China' },
    { id: 171, text: 'A magical winter wonderland at night' },
    { id: 172, text: 'A breathtaking mountain range in Patagonia' },
    { id: 173, text: 'A vibrant spring meadow filled with wildflowers' },
    { id: 174, text: 'A serene lake reflecting the autumn foliage' },
    { id: 175, text: 'A tropical rainforest teeming with wildlife' },
    { id: 176, text: 'A bustling Chinatown during Lunar New Year' },
    { id: 177, text: 'A majestic palace in Rajasthan' },
    { id: 178, text: 'A picturesque vineyard in Napa Valley' },
    { id: 179, text: 'A quiet monastery in Tibet' },
    { id: 180, text: 'A lively jazz club in New Orleans' },
    { id: 181, text: 'A peaceful lavender field in Provence' },
    { id: 182, text: 'A charming old street in Bruges' },
    { id: 183, text: 'A bustling sushi restaurant in Tokyo' },
    { id: 184, text: 'A tranquil koi pond in a Japanese garden' },
    { id: 185, text: 'A magical Harry Potter-like library' },
    { id: 186, text: 'A tranquil oasis in the Sahara Desert' },
    { id: 187, text: 'A lively tapas bar in Seville' },
    { id: 188, text: 'A magical fairy glen in Scotland' },
    { id: 189, text: 'A peaceful night in the Sahara under a starlit sky' },
    { id: 190, text: 'A bustling street in the heart of Marrakech' },
    { id: 191, text: 'A sunken pirate ship under the sea' },
    { id: 192, text: 'A medieval blacksmith’s workshop' },
    { id: 193, text: 'A romantic gondola ride in Venice' },
    { id: 194, text: 'A peaceful yoga retreat in Bali' },
    { id: 195, text: 'A rustic vineyard in the French countryside' },
    { id: 196, text: 'A secret lagoon hidden in a tropical island' },
    { id: 197, text: 'A quiet reading room in a grand library' },
    { id: 198, text: 'A scenic hiking trail in the Rockies' },
    { id: 199, text: 'A bustling night market in Taipei' },
    { id: 200, text: 'A quiet chapel in an old European town' },
    { id: 201, text: 'A tranquil lake in the mountains' },
    { id: 202, text: 'A bustling street in Tokyo at night' },
    { id: 203, text: 'A peaceful pagoda in the mountains' },
    { id: 204, text: 'A quiet café in a quaint European town' },
    { id: 205, text: 'A bustling street market in Bangkok' },
    { id: 206, text: 'A quiet cabin in the woods' },
    { id: 207, text: 'A bustling street in Hong Kong' },
    { id: 208, text: 'A quiet street in a European village' },
  ],
  artStyle: [
    { id: 1, text: 'professional photography' },
    { id: 2, text: 'advertising photography' },
    { id: 3, text: 'pixel-art' },
    { id: 4, text: 'watercolor' },
    { id: 5, text: 'illustration' },
    { id: 6, text: 'macro photography' },
    { id: 7, text: 'cinematic portrait' },
    { id: 8, text: 'contre-jour' },
    { id: 9, text: 'cinematic still' },
    { id: 10, text: 'comic' },
    { id: 11, text: 'halftone' },
    { id: 12, text: 'woodblock print' },
    { id: 13, text: 'carved leather' },
    { id: 14, text: 'logo' },
    { id: 15, text: 'kirigami' },
    { id: 16, text: 'origami' },
    { id: 17, text: 'layered paper' },
    { id: 18, text: 'editorial photo' },
    { id: 19, text: 'cartoon' },
    { id: 20, text: 'anime' },
    { id: 21, text: 'architecture' },
    { id: 22, text: 'sculpture' },
    { id: 23, text: 'drone photography' },
    { id: 24, text: 'isometric' },
    { id: 25, text: 'matte painting' },
    { id: 26, text: 'abstract' },
    { id: 27, text: 'expressionism' },
    { id: 28, text: 'digital painting' },
    { id: 29, text: '3d painting' },
    { id: 30, text: 'doodle' },
    { id: 31, text: 'hand-drawn' },
    { id: 32, text: 'game art' },
    { id: 33, text: 'vector' },
    { id: 34, text: 'sketch' },
    { id: 35, text: '2d' },
    { id: 36, text: '3d' },
    { id: 37, text: 'collage' },
    { id: 38, text: 'acrylic' },
    { id: 39, text: 'caricature' },
    { id: 40, text: 'mockup' },
    { id: 41, text: 'graphic novel' },
    { id: 42, text: 'template' },
    { id: 43, text: 'sprite sheet' },
    { id: 44, text: '3d model' },
    { id: 45, text: 'flat animation' },
    { id: 46, text: 'manga' },
  ],
  mood: [
    { id: 1, text: 'beauty' },
    { id: 2, text: 'elegance' },
    { id: 3, text: 'classical' },
    { id: 4, text: 'golden ratio' },
    { id: 5, text: 'close-up' },
    { id: 6, text: 'extreme close-up' },
    { id: 7, text: 'glowflow' },
    { id: 8, text: 'award-winning' },
    { id: 9, text: 'cinematic lighting' },
    { id: 10, text: 'minimalism' },
    { id: 11, text: 'light leaks' },
    { id: 12, text: 'glitch' },
    { id: 13, text: 'bokeh' },
    { id: 14, text: 'gritty' },
    { id: 15, text: 'urban' },
    { id: 16, text: 'muted colors' },
    { id: 17, text: 'intricate details' },
    { id: 18, text: 'layered composition' },
    { id: 19, text: 'transcendence' },
    { id: 20, text: 'neon' },
    { id: 21, text: 'cinematic' },
    { id: 22, text: 'luxurious' },
    { id: 23, text: 'kodak potra' },
    { id: 24, text: 'random' },
    { id: 25, text: 'candid' },
    { id: 26, text: 'captivating' },
    { id: 27, text: 'otherworldly' },
    { id: 28, text: 'sun-rays' },
    { id: 29, text: 'reflection' },
    { id: 30, text: 'volumetric lighting' },
    { id: 31, text: 'emotionally-charged' },
    { id: 32, text: 'exaggerated-expressions' },
    { id: 33, text: 'quirky' },
    { id: 34, text: 'dignified pose' },
    { id: 35, text: 'kinetic' },
    { id: 36, text: 'surreal' },
    { id: 37, text: 'inflatable' },
    { id: 38, text: 'translucent' },
    { id: 39, text: 'fluorescent' },
    { id: 40, text: 'bioluminescent' },
    { id: 41, text: 'playful' },
    { id: 42, text: 'futuristic' },
    { id: 43, text: 'retro' },
    { id: 44, text: 'natural lighting' },
    { id: 45, text: 'symmetrical' },
    { id: 46, text: 'aesthetic' },
    { id: 47, text: 'amazing' },
    { id: 48, text: 'biomorphic' },
    { id: 49, text: 'blacklight' },
    { id: 50, text: 'phantasmal irisdecent' },
    { id: 51, text: 'psychedelic' },
    { id: 52, text: 'cute' },
    { id: 53, text: 'kawaii' },
    { id: 54, text: 'cheerful colors' },
    { id: 55, text: 'intense gaze' },
    { id: 56, text: 'noir' },
    { id: 57, text: 'sci-fi' },
    { id: 58, text: 'countryside' },
    { id: 59, text: 'haunting elegance' },
    { id: 60, text: 'dreamlike' },
    { id: 61, text: 'fire' },
    { id: 62, text: 'pattern' },
    { id: 63, text: 'earthy' },
    { id: 64, text: 'beachy' },
    { id: 65, text: 'wintery' },
    { id: 66, text: 'chaos' },
    { id: 67, text: 'bold linework' },
    { id: 68, text: 'draw style' },
    { id: 69, text: 'pretty' },
    { id: 70, text: 'handsome' },
    { id: 71, text: 'horror' },
    { id: 72, text: 'afrofuturism' },
    { id: 73, text: 'hyper-detailed' },
    { id: 74, text: 'ultra-realistic' },
    { id: 75, text: 'zbrush' },
    { id: 76, text: 'unreal' },
    { id: 77, text: 'hdr' },
    { id: 78, text: '4k' },
    { id: 79, text: 'junglejazz' },
    { id: 80, text: 'rubik' },
    { id: 81, text: 'paraphernalia' },
    { id: 82, text: 'maya render' },
    { id: 83, text: 'multichromatic' },
    { id: 84, text: 'white background' },
    { id: 85, text: 'industrial' },
    { id: 86, text: 'brick' },
    { id: 87, text: 'cobble' },
    { id: 88, text: 'wood' },
    { id: 89, text: 'high-end' },
    { id: 90, text: 'silhouette' },
    { id: 91, text: 'sharp edges' },
    { id: 92, text: 'fog' },
    { id: 93, text: 'stylized' },
    { id: 94, text: 'rural' },
    { id: 95, text: 'zen' },
    { id: 96, text: 'gloomy' },
    { id: 97, text: 'dark' },
    { id: 98, text: 'blurred' },
    { id: 99, text: 'Victorian' },
    { id: 100, text: 'extravagant' },
    { id: 101, text: 'nautical' },
    { id: 102, text: 'maritime' },
    { id: 103, text: 'Bohemian' },
    { id: 104, text: 'whimsical' },
    { id: 105, text: 'colorful' },
    { id: 106, text: 'icon' },
    { id: 107, text: 'avatar' },
    { id: 108, text: 'magical' },
    { id: 109, text: 'action' },
    { id: 110, text: 'dynamic' },
    { id: 111, text: 'gears' },
    { id: 112, text: 'armor' },
    { id: 113, text: 'grandeur' },
    { id: 114, text: 'layered textures' },
    { id: 115, text: 'soft' },
    { id: 116, text: 'ink' },
    { id: 117, text: 'ethereal' },
    { id: 118, text: 'dreamy' },
    { id: 119, text: 'mysterious' },
    { id: 120, text: 'monochrome' },
    { id: 121, text: 'medieval' },
    { id: 122, text: 'cozy' },
    { id: 123, text: 'peaceful' },
    { id: 124, text: 'underwater' },
    { id: 125, text: 'mystical' },
    { id: 126, text: 'eerie' },
    { id: 127, text: 'b&w' },
    { id: 128, text: 'fluid' },
    { id: 129, text: 'low detail' },
    { id: 130, text: 'woodcut' },
    { id: 131, text: 'grayscale' },
    { id: 132, text: 'letterboxing' },
    { id: 133, text: 'detailed skies' },
    { id: 134, text: 'shadows' },
    { id: 135, text: 'romantic' },
    { id: 136, text: 'flora' },
    { id: 137, text: 'fauna' },
    { id: 138, text: 'morning light' },
    { id: 139, text: 'modern' },
    { id: 140, text: 'behance' },
    { id: 141, text: 'rounded' },
    { id: 142, text: 'simple' },
    { id: 143, text: 'warm palette' },
    { id: 144, text: 'cool palette' },
    { id: 145, text: 'Chibi' },
    { id: 146, text: 'realistic' },
    { id: 147, text: 'cartoony' },
    { id: 148, text: 'sharp contrast' },
    { id: 149, text: 'gold' },
    { id: 150, text: 'ruby' },
    { id: 151, text: 'emerald' },
    { id: 152, text: 'sapphire' },
    { id: 153, text: 'silver' },
    { id: 154, text: 'diamond' },
    { id: 155, text: 'stealth' },
    { id: 156, text: 'synthwave' },
    { id: 157, text: 'serenity' },
    { id: 158, text: 'glossy' },
    { id: 159, text: 'fluffy' },
    { id: 160, text: 'gross' },
    { id: 161, text: 'twisted' },
    { id: 162, text: 'nightmarish' },
    { id: 163, text: 'punk-inspired' },
    { id: 164, text: 'frayed' },
    { id: 165, text: 'liquid' },
    { id: 166, text: 'flowing' },
    { id: 167, text: 'glowing' },
    { id: 168, text: 'pixelated chaos' },
    { id: 169, text: 'Ghibli' },
    { id: 170, text: 'hallucinations' },
    { id: 171, text: 'vhs' },
    { id: 172, text: 'trapped emotions' },
    { id: 173, text: 'distorted' },
    { id: 174, text: 'stunning' },
    { id: 175, text: 'national geographic' },
    { id: 176, text: 'pixar' },
    { id: 177, text: 'brown paper' },
    { id: 178, text: 'folk' },
    { id: 179, text: 'Dadaist' },
    { id: 180, text: 'masterpiece' },
    { id: 181, text: 'glittercore' },
    { id: 182, text: 'daydreampunk' },
    { id: 183, text: 'Steampunk' },
    { id: 184, text: 'cyberpunk' },
    { id: 185, text: 'rainbowcore' },
    { id: 186, text: 'manapunk' },
    { id: 187, text: 'solarpunk' },
    { id: 188, text: 'junglecore' },
    { id: 189, text: 'zombiecore' },
    { id: 190, text: 'royalcore' },
    { id: 191, text: 'poolcore' },
    { id: 192, text: 'gardencore' },
    { id: 193, text: 'cottagecore' },
    { id: 194, text: 'cabincore' },
    { id: 195, text: 'havencore' },
    { id: 196, text: 'seapunk' },
    { id: 197, text: 'animecore' },
    { id: 198, text: 'weirdcore' },
    { id: 199, text: 'chromepunk' },
    { id: 200, text: 'trashcore' },
    { id: 201, text: 'glitchcore' },
  ],
};
